[controls]
up = "Up"
down = "Down"
left = "Left"
right = "Right"
camera-speed = 64.0
item-offset = false

[graphics]
always-show-stack-size = false
d3-scale = 256 
instance-cloth = true

[tile]
grass-growth-time = 60.0
 
[plants.wheat]
growth-time = 10.0 
